---

Hub:
    hostname: 10.188.188.201
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Hub

Spoke1:
    hostname: 10.188.188.202
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Spoke2:
    hostname: 10.188.188.203
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Spoke3:
    hostname: 10.188.188.204
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Spoke4:
    hostname: 10.188.188.205
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Spoke5:
    hostname: 10.188.188.206
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Spoke6:
    hostname: 10.188.188.207
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: Spoke

Core1:
    hostname: 10.188.188.208
    groups:
        - cisco_group
    data:
        domain: ipvzero
        site: central

Core2:
    hostname: 10.188.188.209
    groups:
        - cisco_group
    data:
        domain: ipvzero
        site: central
