---

inventory:
    plugin: SimpleInventory
    options:
        #CHANGE THESE PATHS
        host_file: "../testhosts.yaml"
        group_file: "../groups.yaml"
        defaults_file: "../defaults.yaml"

runners:
    plugin: threaded
    options:
        num_workers: 10

logging:
  enabled: False
